In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, cross_val_score, cross_validate
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, confusion_matrix, make_scorer
import pandas as pd
import numpy as np

In [2]:
iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = pd.Series(iris.target)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=2)

In [5]:
def print_performance(y_pred):
  acc = accuracy_score(y_test, y_pred)
  precision = precision_score(y_test, y_pred, average='weighted')
  recall = recall_score(y_test, y_pred, average='weighted')
  f1 = f1_score(y_test, y_pred, average='weighted')
  conf_matrix = confusion_matrix(y_test, y_pred)

  print(f"Accuracy: {acc * 100:.2f}%")
  print(f"Precision: {precision:.2f}")
  print(f"Recall: {recall:.2f}")
  print(f"F1-Score: {f1:.2f}")
  print("Confusion Matrix:")
  print(conf_matrix)


###KNN classifier without 10 fold cross validation ( using library )

In [6]:
k = 3 # adjust the value of k here
knn = KNeighborsClassifier(k)
knn.fit(X_train,y_train)

y_pred = knn.predict(X_test)
print_performance(y_pred)


Accuracy: 100.00%
Precision: 1.00
Recall: 1.00
F1-Score: 1.00
Confusion Matrix:
[[14  0  0]
 [ 0  8  0]
 [ 0  0  8]]


In [7]:
k = 5 # adjust the value of k here
knn = KNeighborsClassifier(k)
knn.fit(X_train,y_train)

y_pred = knn.predict(X_test)
print_performance(y_pred)

Accuracy: 100.00%
Precision: 1.00
Recall: 1.00
F1-Score: 1.00
Confusion Matrix:
[[14  0  0]
 [ 0  8  0]
 [ 0  0  8]]


###KNN classifier without 10 fold cross validation ( using library )

In [10]:
def print_evaluation(cv_results):
  print("Evaluation Metrics (10-Fold Cross-Validation):")
  print(f"Accuracy: {cv_results['test_accuracy'].mean():.4f}")
  print(f"Precision (Macro): {cv_results['test_precision_macro'].mean():.4f}")
  print(f"Recall (Macro): {cv_results['test_recall_macro'].mean():.4f}")
  print(f"F1-Score (Macro): {cv_results['test_f1_macro'].mean():.4f}")

In [13]:
k = 3
knn = KNeighborsClassifier(n_neighbors=k)

# Perform 10-fold cross-validation and compute evaluation metrics
scoring = ['accuracy', 'precision_macro', 'recall_macro', 'f1_macro']
cv_results = cross_validate(knn, X, y, cv=10, scoring=scoring)
print_evaluation(cv_results)


Evaluation Metrics (10-Fold Cross-Validation):
Accuracy: 0.9667
Precision (Macro): 0.9738
Recall (Macro): 0.9667
F1-Score (Macro): 0.9659


In [14]:
k = 5
knn = KNeighborsClassifier(n_neighbors=k)

# Perform 10-fold cross-validation and compute evaluation metrics
scoring = ['accuracy', 'precision_macro', 'recall_macro', 'f1_macro']
cv_results = cross_validate(knn, X, y, cv=10, scoring=scoring)
print_evaluation(cv_results)


Evaluation Metrics (10-Fold Cross-Validation):
Accuracy: 0.9667
Precision (Macro): 0.9738
Recall (Macro): 0.9667
F1-Score (Macro): 0.9659
